% Example of type annations generated by TypEr lib for a small FIFO implementation.
-spec new() -> {'fifo', [], []}.
-spec push({'fifo', _, _}, _) -> {'fifo', nonempty_maybe_improper_list(), _}.
-spec pop({'fifo', _, maybe_improper_list(), _}) -> {_, {'fifo', _, _}}.
-spec empty({'fifo', _, _}) -> bool().
